export declare const authServerBase = "/auth/v1";
export declare const dataEngineBase = "/data-engine/v4";
export declare const geocodeBase = "/geocoder/v1";
export declare const datasetGeneratorBase = "/dataset-generator/v1";
export declare const simulationControlBase = "/model-engine/v1";
declare const _default: {
    activate: string;
    activityLogs: string;
    autocomplete: string;
    analysisPlot: string;
    control: string;
    data: string;
    datasets: string;
    dataset_types: string;
    entity_types: string;
    feedback_form: string;
    forgotpassword: string;
    generate: string;
    generators: string;
    initdata: string;
    invite: string;
    login: string;
    logout: string;
    logs: string;
    map: string;
    modelTypes: string;
    organisations: string;
    projects: string;
    profile: string;
    property_types: string;
    resetpassword: string;
    results: string;
    reverseSearch: string;
    roles: string;
    runSimulation: string;
    scenarios: string;
    schema: string;
    scopes: string;
    search: string;
    simulations: string;
    state: string;
    summary: string;
    timeline: string;
    updates: string;
    users: string;
    validateAuth: string;
    views: string;
    workloads: string;
};
export default _default;
